version: '3'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: pwd
      MARIADB_DATABASE: users_db
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mariadb_data:
    driver: local
